export const businesses = [
  {
    id: 'b1',
    name: 'Apex Digital Print Studio',
    slug: 'apex-digital-print-studio',
    verified: true,
    category: 'Digital Printing',
    rating: 4.8,
    reviews: 156,
    area: 'Himayatnagar',
    city: 'Hyderabad',
    state: 'Telangana',
    distance: '2.4',
    about: 'Apex Digital Print Studio is a premium printing facility offering high-speed, high-quality digital printing for corporate and individual needs. We specialize in fast turnarounds and bulk orders without compromising on color accuracy.',
    phone: '+91 800 888 6365',
    whatsapp: '+91 800 888 6365',
    email: 'hello@apexprint.com',
    website: 'www.apexprintstudio.com',
    address: '12-3-45, Main Road, Himayatnagar, Hyderabad, Telangana 500029',
    services: ['Large Format Printing', 'Business Cards', 'Brochures', 'Flyers'],
    materials: ['Paper', 'Vinyl', 'Card'],
    isOpen: true
  },
  {
    id: 'b2',
    name: 'Creative 3D Hub',
    slug: 'creative-3d-hub',
    verified: true,
    category: '3D Printing',
    rating: 4.9,
    reviews: 89,
    area: 'Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    distance: '5.1',
    about: 'Specialized in rapid prototyping and custom 3D models. We print using SLA and FDM technologies.',
    phone: '+91 900 111 2222',
    whatsapp: '+91 900 111 2222',
    email: 'contact@creative3d.com',
    website: 'www.creative3dhub.in',
    address: 'Road No 12, Banjara Hills, Hyderabad, Telangana 500034',
    services: ['Prototyping', 'Custom Models', 'Miniatures'],
    materials: ['Plastic', 'Resin'],
    isOpen: false
  },
  {
    id: 'b3',
    name: 'Neon Laser Cutters',
    slug: 'neon-laser-cutters',
    verified: false,
    category: 'Laser Cutting',
    rating: 4.5,
    reviews: 42,
    area: 'Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    distance: '7.8',
    about: 'High precision CNC and Laser cutting services for acrylic, MDF, and metals.',
    phone: '+91 999 888 7777',
    whatsapp: '+91 999 888 7777',
    email: 'info@neonlaser.com',
    website: 'www.neonlaser.com',
    address: 'Plot 45, Jubilee Hills, Hyderabad',
    services: ['CNC Routing', 'Laser Engraving', 'Signage Boards'],
    materials: ['Acrylic', 'MDF', 'Metal', 'Wood'],
    isOpen: true
  }
];